name: CI Build

on:
  workflow_call:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    name: Build-${{ matrix.os }}
    concurrency:
      group: ${{ matrix.os }}-build-${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy,rustfmt
      - name: check
        run: cargo fmt --all -- --check
      - name: lint
        run: cargo clippy -- -D warnings
