name: CI Build
# Controls when the workflow will be run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:     
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Map Azure File Share
        run: |
        net use Z: \\<StorageAccountName>.file.core.windows.net\u<AzureFileShareName> /user:<StorageAccountName> ${{ secrets.AZURE_STORAGE_KEY }}
      - name: Install Visual Studio Build Tools
        run: choco install visualstudio2022buildtools --package-parameters "--wait --quiet --addProductLang En-us --config Z:\config\v143-14.34-buildtools.vsconfig"
      - name: Setup MSVC v143 14.34 build tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.34
          arch: x64
      - name: Build with Unreal
        uses: OrchidIsle/UE5-Build-Project@0.2.2
        with:
          RUNUAT_PATH: 'Z:/UE_5.3/Engine/Build/BatchFiles/RunUAT.bat'
          UPROJECT_PATH: ${{ github.workspace }}/<ProjectName>.uproject
          BUILD_CONFIG: Development
          PLATFORM: Win64
          COOK: false
          STAGE: false
